# Generated by Django 4.1.2 on 2022-11-18 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date_published',
            new_name='pub_date',
        ),
    ]
